tasks:
  - name: Setup Kubernetes with kind
    init: |
      # Install Docker
      curl -fsSL https://get.docker.com | sh
      sudo usermod -aG docker gitpod

      # Install kind
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.22.0/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind

      # Install kubectl
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      chmod +x kubectl
      sudo mv kubectl /usr/local/bin/kubectl

      # Create cluster
      kind create cluster --name interview --wait 60s
    command: |
      kubectl get nodes
ports:
  - port: 30000-32767
    onOpen: ignore
